### ISSUE TITLE
Crash on many projectiles

### ISSUE THREAD

**Issue by Skratzy** [BTH-StoraSpel-DXR/SPLASH#209]
When too many projectiles are live at the same time the game crashes.

To reproduce:
Go into PerformanceTest and press P to make all entities shoot projectiles at the same time

**Comment by tofb15** [comment]
Believe the issue is that the octree is updated while other systems is using it. The octree update resizes vectors making their content invalid.

Fixed in commit: https://github.com/BTH-StoraSpel-DXR/SPLASH/commit/d81632972e0f9e2374fa7373c434509dfea7e21e
