### ISSUE TITLE
Metaballs is only rendered near the middle of the screen when gbuffer pass is enabled.

### ISSUE THREAD

**Issue by Praccen** [BTH-StoraSpel-DXR/SPLASH#263]
To reproduce: Shoot some water. Angle the camera away from the projectiles.

**Comment by tofb15** [comment]
Har med denna raden att göra.
När Gbufferpasset och Metaballs bilden mergas jämförs djupet på pixlarna. Djupen är dock i olika scalor så gjorde bara en quickfix.

metaballDepth måste få ett värde som går att jämföra linjärt med linearDepth.

https://github.com/BTH-StoraSpel-DXR/SPLASH/blob/5a459d32fd071c7f4c5d108cd8d6e33edba7c4a5/SPLASH/res/shaders/dxr/Basic.hlsl#L137

**Comment by Piratkopia13** [comment]
@Praccen seemingly fixed the problem by subtracting the projection of the closest hit value relative to the camera onto the camera direction, instead of CB_SceneData.nearZ * 4
