### ISSUE TITLE
Pressing F10 while ImGui flimmers crashes the program.

### ISSUE THREAD

**Issue by DanielFredriksson** [BTH-StoraSpel-DXR/SPLASH#344]
Run enough applications on the same computer (not on release) until the flimmer appears. When in-game, press F10 and that client will crash.

**Comment by Piratkopia13** [comment]
imgui flimmer is caused by the screen space renderer. Investigation in progress 🕵

**Comment by Piratkopia13** [comment]
should be fixed in pr #360

**Comment by Piratkopia13** [comment]
if anyone still gets this crash - please post a screenshot of the crash with callstack here
