### ISSUE TITLE
Game crashes if there is no audio output device in Windows

### ISSUE THREAD

**Issue by viktor4006094** [BTH-StoraSpel-DXR/SPLASH#345]
To replicate disable all audio output devices in windows and start a match

**Comment by viktor4006094** [comment]
Still crashes in the Release configuration on latest dev f4f2f2b2dc923a4c9ad1e27fdfafc57ac308d007

**Comment by whalemane** [comment]
#482

**Comment by viktor4006094** [comment]
fixed in #482
