### ISSUE TITLE
player dont loose when candle die sometimes

### ISSUE THREAD

**Issue by Discojanne** [BTH-StoraSpel-DXR/SPLASH#352]
Playing 4 players on the same computer -> sometimes player doesnt loost when candle dies,

**Comment by whalemane** [comment]
Probably related to #292

**Comment by soridanm** [comment]
Will we ever play 4 player on the same computer except for testing purpouses?

**Comment by viktor4006094** [comment]
If this was still a bug it was fixed in #470
