### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Piratkopia13** [BTH-StoraSpel-DXR/SPLASH#395]
We seem to have a memory leak, possibly from projectiles not being removed correctly. Very obvious when running performance test. 

![image](https://user-images.githubusercontent.com/6361662/67845132-3ee04380-faff-11e9-86d0-2bc386ce28f9.png)

These are the new allocations after a profiling from ~20 seconds
![image](https://user-images.githubusercontent.com/6361662/67845391-b31ae700-faff-11e9-9873-663f56779cec.png)

**Comment by tofb15** [comment]
Projectiles are removed correctly from all systems.
![Capture](https://user-images.githubusercontent.com/24247942/67850071-efeadc00-fb07-11e9-96f4-3d19f9c2b938.PNG)

Might be leaks in sound engine but i am still looking for the issue.

**Comment by tofb15** [comment]
If audiosystem->update is removed the leak disappear.

**Comment by tofb15** [comment]
@OliverGlandberger

**Comment by viktor4006094** [comment]
presumably fixed in #442 or before that
