### ISSUE TITLE
Intermittent crashes while playing online

### ISSUE THREAD

**Issue by whalemane** [BTH-StoraSpel-DXR/SPLASH#407]

**Comment by Piratkopia13** [comment]
![image](https://user-images.githubusercontent.com/6361662/67859342-aefcc280-fb1b-11e9-9a36-ee36965f426c.png)

**Comment by Piratkopia13** [comment]
Also happens when in the main menu. I left the game open in debug for a bit and it crashed
![image](https://user-images.githubusercontent.com/6361662/67860583-82967580-fb1e-11e9-97f0-1a946be82654.png)

**Comment by viktor4006094** [comment]
Fixed in 9a68af34b25a1db7d5f7f5704b4d6c808e508ff7
