### ISSUE TITLE
Textures (mip levels) wrong when using ScreenSpaceRenderer

### ISSUE THREAD

**Issue by Skratzy** [BTH-StoraSpel-DXR/SPLASH#426]
All players except the host get the left view when rendering GUI using ScreenSpaceRenderer

![image](https://user-images.githubusercontent.com/6361661/68106157-02d32700-fee1-11e9-8652-18a7aa0874d8.png)

**Comment by Skratzy** [comment]
Only appears when you run multiple clients on the same computer

**Comment by Skratzy** [comment]
From other issue
![image](https://user-images.githubusercontent.com/6361661/68870260-e3b37100-06fa-11ea-9d8b-8d8f7a5353ec.png)

![image](https://user-images.githubusercontent.com/6361661/68870267-e746f800-06fa-11ea-847f-8705323483c8.png)

**Comment by Skratzy** [comment]
Probably cause: Something breaking with mip generation
![image](https://user-images.githubusercontent.com/6361661/68870294-f5951400-06fa-11ea-914f-e14dc2cf546e.png)

**Comment by whalemane** [comment]
Est: 5
