### ISSUE TITLE
The 'KillFeed' displays false kills at the start of games played after the same one.

### ISSUE THREAD

**Issue by DanielFredriksson** [BTH-StoraSpel-DXR/SPLASH#461]
Steps to reproduce:
1. Start two applications as release or dev-release.
2. Play the match as usual.
3. After the game is finished, play another game.

**Comment by DanielFredriksson** [comment]
![image](https://user-images.githubusercontent.com/22372845/68482830-abafb800-023a-11ea-864b-d9eca5c17a9d.png)

**Comment by tofb15** [comment]
Fixed in: https://github.com/BTH-StoraSpel-DXR/SPLASH/pull/475
