### ISSUE TITLE
Bad performance on small maps

### ISSUE THREAD

**Issue by viktor4006094** [BTH-StoraSpel-DXR/SPLASH#464]
With a 2x2 map size the frame rate is much lower than it should be even though the `Compute_1` utilization on the GPU is at 99%

**Comment by h3nx** [comment]
might be because of the watergrid
gridsize is constant, making water hit multiple indices at the same time(?)

**Comment by tofb15** [comment]
What does the profiler say?

**Comment by whalemane** [comment]
Est: 0

**Comment by viktor4006094** [comment]
Fixed in #573
