### ISSUE TITLE
Killing a player crashes the game. [DEBUG]

### ISSUE THREAD

**Issue by DanielFredriksson** [BTH-StoraSpel-DXR/SPLASH#469]

**Comment by DanielFredriksson** [comment]
![image](https://user-images.githubusercontent.com/22372845/68482830-abafb800-023a-11ea-864b-d9eca5c17a9d.png)

**Comment by DanielFredriksson** [comment]
Already fixed by Victor in a branch far far away.

**Comment by viktor4006094** [comment]
fixed in #470
