### ISSUE TITLE
Candle can be placed under the map.

### ISSUE THREAD

**Issue by tofb15** [BTH-StoraSpel-DXR/SPLASH#523]
By just pressing F fast the candles can be placed under the floor and start falling forever.

![Capture](https://user-images.githubusercontent.com/24247942/68860535-fa9d9780-06e9-11ea-8ce4-f3856a449b8c.PNG)

**Comment by Skratzy** [comment]
Happens rather often

**Comment by Praccen** [comment]
This is because of ray casted collisions not working properly with the torch's bounding box. Will be fixed when proper physics for the torch is implemented.

**Comment by whalemane** [comment]
Est: 1
