### ISSUE TITLE
Crosshair breaks textures.

### ISSUE THREAD

**Issue by DanielFredriksson** [BTH-StoraSpel-DXR/SPLASH#527]

**Comment by DanielFredriksson** [comment]
![image](https://user-images.githubusercontent.com/22372845/68866062-21f96200-06f4-11ea-9460-2f9e468161a9.png)

**Comment by DanielFredriksson** [comment]
![image](https://user-images.githubusercontent.com/22372845/68866213-5bca6880-06f4-11ea-9415-64cc4bce2859.png)

**Comment by Skratzy** [comment]
Mip generation

![image](https://user-images.githubusercontent.com/6361661/68866489-cb405800-06f4-11ea-95bd-68fcfd024bda.png)

**Comment by Skratzy** [comment]
This is the same as #426, closing.
