### ISSUE TITLE
Clear color should be black. Looks weird for spectators.

### ISSUE THREAD

**Issue by whalemane** [BTH-StoraSpel-DXR/SPLASH#535]

**Comment by viktor4006094** [comment]
In the spectator mode? I kind of like the grey void outside the map

**Comment by whalemane** [comment]
It should be darker anyway, it looks unfinished with the floating map as it is, imo

**Comment by tofb15** [comment]
**Super Black**
![0](https://user-images.githubusercontent.com/24247942/69368629-c6524a00-0c9a-11ea-9b96-7792fffe0143.PNG)
**Black**
![1](https://user-images.githubusercontent.com/24247942/69368630-c6eae080-0c9a-11ea-834d-c9ea9e269014.PNG)
**Dark Grey**
![2](https://user-images.githubusercontent.com/24247942/69368634-c6eae080-0c9a-11ea-9575-a8187951e094.PNG)
**Grey**
![3](https://user-images.githubusercontent.com/24247942/69368635-c6eae080-0c9a-11ea-990a-57620251aa1a.PNG)
**Light Grey**
![4](https://user-images.githubusercontent.com/24247942/69368636-c7837700-0c9a-11ea-9e92-f5707aae4224.PNG)
**White**
![5](https://user-images.githubusercontent.com/24247942/69368637-c7837700-0c9a-11ea-9847-4e73be0fcba5.PNG)
