### ISSUE TITLE
Crash when spectating and flying around in the map.

### ISSUE THREAD

**Issue by Praccen** [BTH-StoraSpel-DXR/SPLASH#536]
Host a game. Kill yourself 3 times to go into spactator mode. Fly around inside the map.

![image](https://user-images.githubusercontent.com/26962810/68885847-3b130a80-0716-11ea-8e8b-d79dce17c639.png)

**Comment by Skratzy** [comment]
Doesn't only happen when spectating

**Comment by viktor4006094** [comment]
Also happened simultaneously for two spectators.

**Comment by whalemane** [comment]
Est: 1

**Comment by whalemane** [comment]
![image](https://user-images.githubusercontent.com/26928041/69130292-8a5b9100-0ab0-11ea-95a4-775651d243f9.png)
 can also crash here
