### ISSUE TITLE
Program freezes before moving to end state. Memory increases forever

### ISSUE THREAD

**Issue by Smaugmuel** [BTH-StoraSpel-DXR/SPLASH#545]

**Comment by Piratkopia13** [comment]
I'm guessing this is the bug where "tempPlacementMap" gets an incorrect size like on this screenshot
![image](https://user-images.githubusercontent.com/6361662/68936344-a1417100-079a-11ea-9d38-ab7e5f019be4.png)

**Comment by Smaugmuel** [comment]
Yes.
When using the []-operator on a map, the key will be created if it does not exist.
This probably means the map.size() is always higher than it should be.
