### ISSUE TITLE
Intermittent crash on streaming sounds.

### ISSUE THREAD

**Issue by whalemane** [BTH-StoraSpel-DXR/SPLASH#554]
Can occur when:
- dropping candles
- opening/closing in-game menu

![image](https://user-images.githubusercontent.com/26928041/68942883-ede07880-07a9-11ea-8e9a-4a7ea5677711.png)

**Comment by whalemane** [comment]
Est: 2

**Comment by DanielFredriksson** [comment]
Fixed in #565

**Comment by whalemane** [comment]
Please don't close issue until they are in dev

**Comment by whalemane** [comment]
Please verify if this is still present

**Comment by whalemane** [comment]
#565 is in dev now
