### ISSUE TITLE
Game freezes when the two last players trade the last kill. I.e Draw

### ISSUE THREAD

**Issue by Praccen** [BTH-StoraSpel-DXR/SPLASH#557]
![image](https://user-images.githubusercontent.com/26962810/68944481-339f4000-07ae-11ea-862f-f41b57f4d7a5.png)

**Comment by tofb15** [comment]
can this be related to: https://github.com/BTH-StoraSpel-DXR/SPLASH/issues/545 ?

**Comment by Praccen** [comment]
Yes. Seems like the same behaivior. Removing this issue.
