### ISSUE TITLE
[CONSISTENT] Crash on player dying with three applications on same computer

### ISSUE THREAD

**Issue by DanielFredriksson** [BTH-StoraSpel-DXR/SPLASH#586]
Happened with three applications running on the same computer on dev-release.

![image](https://user-images.githubusercontent.com/22372845/69156832-58642200-0ae4-11ea-96a0-d4a81992c943.png)

**Comment by soridanm** [comment]
replicated once, unable to replicate afterwards.

**Comment by soridanm** [comment]
"The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action. The GPU will not respond to more commands, most likely because of an invalid command passed by the calling application."

**Comment by soridanm** [comment]
doesn't happen online so far
