### ISSUE TITLE
Datatracker not tracking "misc stats" correctly over network.

### ISSUE THREAD

**Issue by tofb15** [BTH-StoraSpel-DXR/SPLASH#601]
Played as client over network.
Longest distance walked by emil: 1137443712M is not correct.

![Capture](https://user-images.githubusercontent.com/24247942/69318090-b572eb80-0c3c-11ea-99a3-72e7ec235435.PNG)

**Comment by viktor4006094** [comment]
Fix for this issue will be included in U530/T667.
When I moved some event emissions out of `ReceiverBase.h` and rewrote some parameters I accidentally changed `distanceWalked` from a float to an int.

**Comment by viktor4006094** [comment]
Fixed in #609
